### ISSUE TITLE
Standalone job master and dashboard intermitten issue

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#127]
Getting following errors when running jobmaster with dashboard for standalone

"SEVERE: Sending HeartBeat message to Dashboard is unsuccessful. for workerID: 2 Response: InboundJaxrsResponse{context=ClientResponse{method=POST, uri=http://localhost:8080/workers/3e2054cc-1c6d-4fac-b0be-fdae88b74388/2/beat/, status=500, reason=Internal Server Error}} 
"[2018-12-20 23:11:13 -0500] [SEVERE] edu.iu.dsc.tws.master.worker.JMWorkerController: Wait limit has been reached. Response message has not been received. 
edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:135)
	at edu.iu.dsc.tws.master.worker.JMWorkerController.sendWorkerListRequest(JMWorkerController.java:124)
	at edu.iu.dsc.tws.master.worker.JMWorkerController.getAllWorkers(JMWorkerController.java:103)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIJobWorkerController.getAllWorkers(MPIJobWorkerController.java:57)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:87)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:407)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:134)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
 
[2018-12-20 23:11:13 -0500] [SEVERE] edu.iu.dsc.tws.api.task.TaskWorker: All workers have not joined the job on the specified time limit: 100000ms. 
edu.iu.dsc.tws.common.exceptions.TimeoutException: All workers have not joined the job on the specified time limit: 100000ms.
	at edu.iu.dsc.tws.master.worker.JMWorkerController.getAllWorkers(JMWorkerController.java:106)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIJobWorkerController.getAllWorkers(MPIJobWorkerController.java:57)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:87)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:407)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:134)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
 
[2018-12-20 23:11:13 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Workers done...   
[2018-12-20 23:11:13 -0500] [SEVERE] edu.iu.dsc.tws.master.worker.JMWorkerController: Wait limit has been reached. Response message has not been received. 
edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:135)
	at edu.iu.dsc.tws.master.worker.JMWorkerController.sendWorkerListRequest(JMWorkerController.java:124)
	at edu.iu.dsc.tws.master.worker.JMWorkerController.getAllWorkers(JMWorkerController.java:103)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIJobWorkerController.getAllWorkers(MPIJobWorkerController.java:57)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:87)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:407)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:134)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
 
[2018-12-20 23:11:13 -0500] [SEVERE] edu.iu.dsc.tws.api.task.TaskWorker: All workers have not joined the job on the specified time limit: 100000ms. 
edu.iu.dsc.tws.common.exceptions.TimeoutException: All workers have not joined the job on the specified time limit: 100000ms.
	at edu.iu.dsc.tws.master.worker.JMWorkerController.getAllWorkers(JMWorkerController.java:106)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIJobWorkerController.getAllWorkers(MPIJobWorkerController.java:57)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:87)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:407)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:134)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
 
[2018-12-20 23:11:13 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Workers done...   
[2018-12-20 23:11:13 -0500] [SEVERE] edu.iu.dsc.tws.api.task.TaskWorker: All workers have not arrived at the barrier on the time limit: 100000ms. 
edu.iu.dsc.tws.common.exceptions.TimeoutException: All workers have not arrived at the barrier on the time limit: 100000ms.
	at edu.iu.dsc.tws.master.worker.JMWorkerController.waitOnBarrier(JMWorkerController.java:175)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIJobWorkerController.waitOnBarrier(MPIJobWorkerController.java:62)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:107)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:407)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:134)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
Caused by: edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:135)
	at edu.iu.dsc.tws.master.worker.JMWorkerController.waitOnBarrier(JMWorkerController.java:171)
	... 5 more
 
[2018-12-20 23:11:13 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Workers done...   
[2018-12-20 23:11:14 -0500] [SEVERE] edu.iu.dsc.tws.master.worker.JMWorkerAgent: Wait limit has been reached. Response message has not been received. 
edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:135)
	at edu.iu.dsc.tws.master.worker.JMWorkerAgent.sendWorkerCompletedMessage(JMWorkerAgent.java:433)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.closeWorker(MPIWorker.java:472)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:135)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
 
[2018-12-20 23:11:14 -0500] [SEVERE] edu.iu.dsc.tws.master.worker.JMWorkerAgent: Wait limit has been reached. Response message has not been received. 
edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:135)
	at edu.iu.dsc.tws.master.worker.JMWorkerAgent.sendWorkerCompletedMessage(JMWorkerAgent.java:433)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.closeWorker(MPIWorker.java:472)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:135)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)
 
[2018-12-20 23:11:14 -0500] [SEVERE] edu.iu.dsc.tws.master.worker.JMWorkerAgent: Wait limit has been reached. Response message has not been received. 
edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:135)
	at edu.iu.dsc.tws.master.worker.JMWorkerAgent.sendWorkerCompletedMessage(JMWorkerAgent.java:433)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.closeWorker(MPIWorker.java:472)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:135)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:202)

**Comment by supunkamburugamuve** [comment]
[out.txt](https://github.com/DSC-SPIDAL/twister2/files/2701479/out.txt)

Attaching the dashboard log that gives errors and when this happens the next job fails with the above errors
