### ISSUE TITLE
IO Exception occurs after 100 jobs submitted

### ISSUE THREAD

**Issue by kannang83** [DSC-SPIDAL/twister2#202]
The IO exception occurs from the task 101 after we submit 100 tasks without cleaning up the java.log file in the home directory. 

kannan@kannan-Precision-5820-Tower-X-Series:~/twister2/bazel-bin/scripts/package/twister2-0.1.0$ ./bin/twister2 submit standalone jar examples/libexamples-java.jar edu.iu.dsc.tws.examples.batch.kmeansoptimization.KMeansJobMain -dinput /tmp/dinput -cinput /tmp/cinput -fShared false -nFiles 1 -dsize 100 -csize 4 -output /tmp/output -workers 2 -dim 2 -parallel 4
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.examples.batch.kmeansoptimization.KMeansJobMain: KMeans Clustering Job  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.core.ResourceAllocator: Loaded configuration with twister2_home: /home/kannan/.cache/bazel/_bazel_kannan/e9508be7717b511160e8bb852071b464/execroot/__main__/bazel-out/k8-fastbuild/bin/scripts/package/twister2-0.1.0 and configuration: /home/kannan/.cache/bazel/_bazel_kannan/e9508be7717b511160e8bb852071b464/execroot/__main__/bazel-out/k8-fastbuild/bin/scripts/package/twister2-0.1.0/conf and cluster: standalone  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.api.Twister2Submitter: The job to be submitted: 
[jobName=KMeans-job], [numberOfWorkers=2]
[workerClass=edu.iu.dsc.tws.examples.batch.kmeansoptimization.KMeansJob]
ComputeResource[0]: cpu: 2.0, ram: 512 MB, disk: 1.0 GB, instances: 2, scalable: false workersPerPod: 1  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.core.ResourceAllocator: Copy core package: /home/kannan/.cache/bazel/_bazel_kannan/e9508be7717b511160e8bb852071b464/execroot/__main__/bazel-out/k8-fastbuild/bin/scripts/package/twister2-0.1.0/dist/twister2-core-0.1.0.tar.gz to /tmp/twister2-KMeans-job-4786078260797306625  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.core.ResourceAllocator: Archive file created: /tmp/twister2-KMeans-job-4786078260797306625/twister2-job.tar.gz  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.core.ResourceAllocator: Initialize uploader  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.core.ResourceAllocator: Calling uploader to upload the package content  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader: Copying job directory at '/tmp/twister2-KMeans-job-4786078260797306625' to target working directory '/home/kannan/.twister2/repository'  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.core.ResourceAllocator: SCP PATH to copy files from: null:/home/kannan/.twister2/repository/  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPILauncher: Launching job for cluster standalone  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPILauncher: Configured as SHARED file system. Skipping bootstrap procedure & setting up working directory  
[2019-01-29 13:43:09 -0500] [INFO] edu.iu.dsc.tws.rsched.utils.ResourceSchedulerUtils: Downloading package /home/kannan/.twister2/repository to /home/kannan/.twister2/jobs/KMeans-job  
[2019-01-29 13:43:10 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPILauncher: Starting the job master: 129.79.186.217:32973  
[2019-01-29 13:43:10 -0500] [WARNING] edu.iu.dsc.tws.master.server.JobMaster: Dashboard host address is null. Not connecting to Dashboard  
[2019-01-29 13:43:10 -0500] [INFO] edu.iu.dsc.tws.common.net.tcp.Server: Starting server on 129-79-186-217.dhcp-bl.indiana.edu:32973  
[2019-01-29 13:43:10 -0500] [INFO] edu.iu.dsc.tws.master.server.JobMaster: JobMaster [129.79.186.217] started and waiting worker messages on port: 32973  
[2019-01-29 13:43:10 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIController: Working directory: /home/kannan/.twister2/jobs  
[2019-01-29 13:43:10 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIController: Launching job in standalone scheduler with no of containers = 2  
[2019-01-29 13:43:10 -0500] [INFO] edu.iu.dsc.tws.rsched.schedulers.standalone.MPICommand: Job class path: /home/kannan/.twister2/jobs/KMeans-job/libexamples-java.jar  
Can't load log handler "java.util.logging.FileHandler"
java.io.IOException: Couldn't get lock for %h/java%u.log, maxLocks: 100
Can't load log handler "java.util.logging.FileHandler"
java.io.IOException: Couldn't get lock for %h/java%u.log, maxLocks: 100
java.io.IOException: Couldn't get lock for %h/java%u.log, maxLocks: 100
	at java.util.logging.FileHandler.openFiles(FileHandler.java:456)
java.io.IOException: Couldn't get lock for %h/java%u.log, maxLocks: 100
	at java.util.logging.FileHandler.<init>(FileHandler.java:281)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:456)
	at java.lang.Class.newInstance(Class.java:442)	at java.util.logging.FileHandler.<init>(FileHandler.java:281)

	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.lang.Class.newInstance(Class.java:442)	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)

	at java.util.logging.Logger.getHandlers(Logger.java:1777)	at java.util.logging.LogManager$5.run(LogManager.java:966)

	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.Logger.log(Logger.java:735)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)	at java.util.logging.Logger.log(Logger.java:788)

	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.loadConfigurations(MPIWorker.java:323)	at java.util.logging.LogManager.access$1500(LogManager.java:145)

	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:102)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:203)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at java.util.logging.Logger.log(Logger.java:735)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.loadConfigurations(MPIWorker.java:323)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:102)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:203)

**Comment by chathurawidanage** [comment]
https://github.com/DSC-SPIDAL/twister2/pull/245
