### ISSUE TITLE
Exception in pinger

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#206]
This exception happens randomly and rarely

Exception in thread "Thread-1" java.lang.NullPointerException
	at edu.iu.dsc.tws.master.worker.Pinger.onMessage(Pinger.java:80)
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient$Handler.onReceiveComplete(RRClient.java:267)
	at edu.iu.dsc.tws.common.net.tcp.DynamicBufferChannel.read(DynamicBufferChannel.java:32)
	at edu.iu.dsc.tws.common.net.tcp.Client.handleRead(Client.java:205)
	at edu.iu.dsc.tws.common.net.tcp.Progress.handleSelectedKeys(Progress.java:98)
	at edu.iu.dsc.tws.common.net.tcp.Progress.loopBlocking(Progress.java:63)
	at edu.iu.dsc.tws.master.worker.JMWorkerAgent.startLooping(JMWorkerAgent.java:252)
	at edu.iu.dsc.tws.master.worker.JMWorkerAgent.access$000(JMWorkerAgent.java:60)
	at edu.iu.dsc.tws.master.worker.JMWorkerAgent$1.run(JMWorkerAgent.java:268)

**Comment by supunkamburugamuve** [comment]
There are few issues in Pinger that are fixed. But it seems there is some other issues as well.

**Comment by chathurawidanage** [comment]
Changed the JM ping interval to 30secs... User should adjust this interval based on the number of workers in his job. If job master fails to send the pong message for 3*interval period of time, Pinger will print a WARN message. This indicates that the job master has been overloaded.
