### ISSUE TITLE
TSet Distributed Mode Issues

### ISSUE THREAD

**Issue by vibhatha** [DSC-SPIDAL/twister2#313]
when tset task hangs due to an exception 
later it gives a Java Heap OutOfMemory exception

`[2019-04-01 17:00:50 -0400] [WARNING] [worker-0] [main] edu.iu.dsc.tws.api.tset.sets.BaseTSet: Overriding parallelism specified 1 override value 1  
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /tmp/java_pid33674.hprof ...
Dump file is incomplete: file size limit
[2019-04-01 17:01:11 -0400] [SEVERE] [worker-0] [main] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Un-expected error 
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at edu.iu.dsc.tws.executor.util.Utils.serialize(Utils.java:64)
	at edu.iu.dsc.tws.executor.core.ExecutionPlanBuilder.createInstances(ExecutionPlanBuilder.java:276)
	at edu.iu.dsc.tws.executor.core.ExecutionPlanBuilder.build(ExecutionPlanBuilder.java:169)
	at edu.iu.dsc.tws.api.task.TaskExecutor.plan(TaskExecutor.java:101)
	at edu.iu.dsc.tws.api.tset.TSetEnv.runAndGet(TSetEnv.java:84)
	at edu.iu.dsc.tws.api.tset.sets.BatchBaseTSet.cache(BatchBaseTSet.java:107)
	at edu.iu.dsc.tws.examples.ml.svm.job.SvmSgdTsetRunner.execute(SvmSgdTsetRunner.java:127)
	at edu.iu.dsc.tws.api.tset.TSetBatchWorker.execute(TSetBatchWorker.java:23)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:104)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:414)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:138)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:204)`

=============================================================================================

When taking outputs from the tset after a reduce, this exception comes

`edu.iu.dsc.tws.common.exceptions.TimeoutException: All workers have not arrived at the barrier on the time limit: 100000ms.
	at edu.iu.dsc.tws.master.worker.JMWorkerController.waitOnBarrier(JMWorkerController.java:192)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIJobWorkerController.waitOnBarrier(MPIJobWorkerController.java:62)
	at edu.iu.dsc.tws.api.task.TaskWorker.execute(TaskWorker.java:107)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:414)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:138)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:204)
Caused by: edu.iu.dsc.tws.common.net.tcp.request.BlockingSendException: Wait limit has been reached. Response message has not been received.
	at edu.iu.dsc.tws.common.net.tcp.request.RRClient.sendRequestWaitResponse(RRClient.java:141)
	at edu.iu.dsc.tws.master.worker.JMWorkerController.waitOnBarrier(JMWorkerController.java:188)
	... 5 more
 
[2019-04-01 20:10:30 -0400] [INFO] [worker-1] [main] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Worker finished executing - 1  `

**Comment by supunkamburugamuve** [comment]
@vibhatha is this issue still there?
