### ISSUE TITLE
Exception in K-Means

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#661]
Getting the following error from time to time when running K-Means.

Command
==========

./bin/twister2 submit standalone jar examples/libexamples-java.jar edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorkerMain -dinput /tmp/dinput -cinput /tmp/cinput -fShared false -nFiles 1 -output /tmp/output -workers 4 -dim 2 -parallelism 4 -filesys local -dsize 100000 -csize 100 -iter 100 -type graph 

Error
======================================================================

2019-10-04 14:00:59 -0400] [SEVERE] [worker-0] [main] edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2: 0 Error in executor 
java.lang.NullPointerException
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.findNearestCenter(KMeansCalculator.java:67)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.calculate(KMeansCalculator.java:56)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker$KMeansSourceTask.execute(KMeansWorker.java:279)
	at edu.iu.dsc.tws.executor.core.batch.SourceBatchInstance.execute(SourceBatchInstance.java:196)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:352)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.access$000(BatchSharingExecutor2.java:315)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.runExecution(BatchSharingExecutor2.java:136)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.execute(BatchSharingExecutor2.java:92)
	at edu.iu.dsc.tws.executor.threading.Executor.execute(Executor.java:65)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:222)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:213)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker.execute(KMeansWorker.java:147)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:423)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:145)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:211)
 
[2019-10-04 14:00:59 -0400] [SEVERE] [worker-0] [main] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Un-expected error 
java.lang.RuntimeException: Error occurred in execution of task
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:362)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.access$000(BatchSharingExecutor2.java:315)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.runExecution(BatchSharingExecutor2.java:136)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.execute(BatchSharingExecutor2.java:92)
	at edu.iu.dsc.tws.executor.threading.Executor.execute(Executor.java:65)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:222)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:213)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker.execute(KMeansWorker.java:147)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:423)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:145)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:211)
Caused by: java.lang.NullPointerException
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.findNearestCenter(KMeansCalculator.java:67)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.calculate(KMeansCalculator.java:56)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker$KMeansSourceTask.execute(KMeansWorker.java:279)
	at edu.iu.dsc.tws.executor.core.batch.SourceBatchInstance.execute(SourceBatchInstance.java:196)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:352)
	... 10 more
 
[2019-10-04 14:00:59 -0400] [SEVERE] [worker-3] [main] edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2: 3 Error in executor 
java.lang.NullPointerException
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.findNearestCenter(KMeansCalculator.java:67)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.calculate(KMeansCalculator.java:56)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker$KMeansSourceTask.execute(KMeansWorker.java:279)
	at edu.iu.dsc.tws.executor.core.batch.SourceBatchInstance.execute(SourceBatchInstance.java:196)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:352)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.access$000(BatchSharingExecutor2.java:315)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.runExecution(BatchSharingExecutor2.java:136)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.execute(BatchSharingExecutor2.java:92)
	at edu.iu.dsc.tws.executor.threading.Executor.execute(Executor.java:65)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:222)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:213)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker.execute(KMeansWorker.java:147)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:423)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:145)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:211)
 
[2019-10-04 14:00:59 -0400] [SEVERE] [worker-3] [main] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Un-expected error 
java.lang.RuntimeException: Error occurred in execution of task
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:362)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.access$000(BatchSharingExecutor2.java:315)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.runExecution(BatchSharingExecutor2.java:136)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2.execute(BatchSharingExecutor2.java:92)
	at edu.iu.dsc.tws.executor.threading.Executor.execute(Executor.java:65)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:222)
	at edu.iu.dsc.tws.task.impl.TaskExecutor.itrExecute(TaskExecutor.java:213)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker.execute(KMeansWorker.java:147)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:423)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:145)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:211)
Caused by: java.lang.NullPointerException
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.findNearestCenter(KMeansCalculator.java:67)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansCalculator.calculate(KMeansCalculator.java:56)
	at edu.iu.dsc.tws.examples.batch.kmeans.KMeansWorker$KMeansSourceTask.execute(KMeansWorker.java:279)
	at edu.iu.dsc.tws.executor.core.batch.SourceBatchInstance.execute(SourceBatchInstance.java:196)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:352)
	... 10 more

**Comment by chathurawidanage** [comment]
Fixed in https://github.com/DSC-SPIDAL/twister2/pull/663
