### ISSUE TITLE
Join example error

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#762]
./bin/twister2 submit standalone jar examples/libexamples-java.jar edu.iu.dsc.tws.examples.task.ExampleTaskMain -itr 1 -workers 2 -size 8 -op "join" -stages 2,2

java.lang.RuntimeException: Collected data for two flags mismatches. FlagA[ALL_SEND] : 1 , FlagB[ALL_RECV] : 2
	at edu.iu.dsc.tws.examples.utils.bench.Timing.verifyTwoFlags(Timing.java:80)
	at edu.iu.dsc.tws.examples.utils.bench.Timing.averageDiff(Timing.java:98)
	at edu.iu.dsc.tws.examples.utils.bench.BenchmarkUtils.markTotalTime(BenchmarkUtils.java:47)
	at edu.iu.dsc.tws.examples.task.batch.BTJoinExample$JoinSinkTask.join(BTJoinExample.java:144)
	at edu.iu.dsc.tws.task.typed.batch.BJoinCompute.execute(BJoinCompute.java:26)
	at edu.iu.dsc.tws.executor.core.batch.TaskBatchInstance.execute(TaskBatchInstance.java:246)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:401)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.access$000(BatchSharingExecutor2.java:364)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchExecution.progress(BatchSharingExecutor2.java:465)
	at edu.iu.dsc.tws.examples.task.BenchTaskWorker.execute(BenchTaskWorker.java:115)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:431)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:146)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:212)
 
[2019-11-22 13:16:35 -0500] [SEVERE] [worker-0] [main] edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker: Un-expected error 
java.lang.RuntimeException: Error occurred in execution of task
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:411)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.access$000(BatchSharingExecutor2.java:364)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchExecution.progress(BatchSharingExecutor2.java:465)
	at edu.iu.dsc.tws.examples.task.BenchTaskWorker.execute(BenchTaskWorker.java:115)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.startWorker(MPIWorker.java:431)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.<init>(MPIWorker.java:146)
	at edu.iu.dsc.tws.rsched.schedulers.standalone.MPIWorker.main(MPIWorker.java:212)
Caused by: java.lang.RuntimeException: Collected data for two flags mismatches. FlagA[ALL_SEND] : 1 , FlagB[ALL_RECV] : 2
	at edu.iu.dsc.tws.examples.utils.bench.Timing.verifyTwoFlags(Timing.java:80)
	at edu.iu.dsc.tws.examples.utils.bench.Timing.averageDiff(Timing.java:98)
	at edu.iu.dsc.tws.examples.utils.bench.BenchmarkUtils.markTotalTime(BenchmarkUtils.java:47)
	at edu.iu.dsc.tws.examples.task.batch.BTJoinExample$JoinSinkTask.join(BTJoinExample.java:144)
	at edu.iu.dsc.tws.task.typed.batch.BJoinCompute.execute(BJoinCompute.java:26)
	at edu.iu.dsc.tws.executor.core.batch.TaskBatchInstance.execute(TaskBatchInstance.java:246)
	at edu.iu.dsc.tws.executor.threading.BatchSharingExecutor2$BatchWorker.runExecution(BatchSharingExecutor2.java:401)
	... 6 more

**Comment by supunkamburugamuve** [comment]
Duplicate issue
